name: monitoring
description: A flutter project concerned with bird ringing data management.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  # provider allows alocation/disposal of resources
  provider: ^6.0.5
  # manage user log in status
  shared_preferences: ^2.1.1 


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



flutter:


  uses-material-design: true

  assets:
    - assets
    - assets/images/
    - .env
