name: monitoring
description: A flutter project concerned with bird ringing data management.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  # provider allows alocation/disposal of resources
  provider: ^6.0.5
  # manage user login status
  shared_preferences: ^2.1.1 
  # path provider for database
  path_provider: ^2.0.15
  # data persistence using sqlite
  drift: ^2.8.0
  # drift initiation libraries
  sqlite3_flutter_libs: ^0.5.15
  # path for database file access
  path: ^1.8.3
  # google maps
  google_maps_flutter: ^2.2.8
  # animation and page changes
  smooth_page_indicator: ^1.1.0
  # GPS access
  # geolocator deprecated in flutter 3.10
  # geolocator: ^9.0.2
  # geocode: ^1.0.3
  location: ^5.0.0
  # internationalize e.g. date
  intl: ^0.18.1
  # create custom type ahead form field
  flutter_typeahead: ^4.6.2


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  drift_dev: ^2.8.2
  test: ^1.22.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - .env
